### ISSUE TITLE
new pipeline structure 

### ISSUE THREAD

**Issue by frank0434** [frank0434/Master#45]
`tar_map` to do a static branching for run 20 jobs in HPC. 

get the first one running. 

relate to #42

**Comment by frank0434** [comment]
- [x] Climate - site depends
- [x] Soil 
    - [x] BD - site depends [Reference](https://github.com/frank0434/Master/blob/b63253164d9f12426e1f98c81f64eb235f73d36e/03Documentations/Manuscript/Chapter4.Rmd#L337-L343)
    - [x] DUL/SAT - site x sowing date depends [Reference](https://github.com/frank0434/Master/blob/b63253164d9f12426e1f98c81f64eb235f73d36e/03Documentations/Manuscript/Chapter4.Rmd#L227)
    - [x] LL/Airdry/LL15 - site x sowing date depends
    - [x] SW - site x sowing date depends
- [x] SowingDate - site x sowing date depends
- [x] CoverFile - site x sowing date depends
- [x] Height - site depends
- [x] Observation process into pipeline. [Reference](https://github.com/frank0434/Master/blob/LucerneBase/03Documentations/Manuscript/Chapter4DataPreparation.Rmd)
- [x] build configuration file 
- [x] test editing 
- [x] testing optimisation function

**Comment by frank0434** [comment]
site depended variables, such as max height and met files, will create multiple targets. 

![image](https://user-images.githubusercontent.com/30789416/116771185-8ef5e880-aa9d-11eb-9d31-de3a019a87c2.png)

**Comment by frank0434** [comment]
> site depended variables, such as max height and met files, will create multiple targets.
> 
> ![image](https://user-images.githubusercontent.com/30789416/116771185-8ef5e880-aa9d-11eb-9d31-de3a019a87c2.png)

because `rep` function did not construct well

**Comment by frank0434** [comment]
`targets` only accept filtering variables as function arguments. won't work as `DT[col1=="xx"]`

**Comment by frank0434** [comment]
BD problem 
![image](https://user-images.githubusercontent.com/30789416/117569830-9c554780-b11b-11eb-9ac7-972abf3aa99b.png)

**Comment by frank0434** [comment]
SOLUTION IS CHANGE BD TO SATISFY SAT 
https://github.com/frank0434/Master/issues/29#issuecomment-773758522

**Comment by frank0434** [comment]
most `bd` and `sat` passed after modify BD xlsx according to the apsimx message, but there're still errors due to incorrect `air-dry` and sat

referred to the ch4 apsimx file, ADSD1 had the high BD and low SAT, passed no issue? 

```
System.Exception: ERROR in file: C:\Data\Master\01Data\ProcessedData\apsimxFiles2021.04.29.22.29.31\temptest.apsimx
Simulation name: AshleyDeneSowingDateSD1
System.Exception: Saturation of 0.305 in layer 5 is above acceptable value of 0.213. You must adjust bulk density to below 1.843 OR saturation to below 0.213
Saturation of 0.370 in layer 18 is above acceptable value of 0.369. You must adjust bulk density to below 1.671 OR saturation to below 0.369
Soil water of 0.153 in layer 3 is below air-dry value of 0.156
Soil water of 0.125 in layer 4 is below air-dry value of 0.138
Soil water of 0.104 in layer 6 is below air-dry value of 0.105
Soil water of 0.112 in layer 8 is below air-dry value of 0.115
Soil water of 0.106 in layer 9 is below air-dry value of 0.139
Soil water of 0.102 in layer 10 is below air-dry value of 0.126
Soil water of 0.104 in layer 11 is below air-dry value of 0.110
Soil water of 0.129 in layer 15 is below air-dry value of 0.162
Soil water of 0.121 in layer 16 is below air-dry value of 0.213
Soil water of 0.124 in layer 17 is below air-dry value of 0.226
Soil water of 0.115 in layer 18 is below air-dry value of 0.249
Soil water of 0.114 in layer 19 is below air-dry value of 0.259
Soil water of 0.114 in layer 20 is below air-dry value of 0.269
Soil water of 0.125 in layer 21 is below air-dry value of 0.275
Soil water of 0.110 in layer 22 is below air-dry value of 0.281

```

**Comment by frank0434** [comment]
#46

**Comment by frank0434** [comment]
```
System.Exception: PredictedObserved: Cannot find any observed data in node: ObsAllData. Check for missing observed file or move ObsAllData to top of child list under DataStore (order is important!)
   at Models.PostSimulationTools.PredictedObserved.Run()
   at Models.Core.Run.SimulationGroup.RunPostSimulationTools()
```

**Need to edit template and add observation path**

**Comment by frank0434** [comment]
12.5 HOURS FOR EACH TREATMENT

**Comment by frank0434** [comment]
the current setup configuration files and apsimx files will be overwritten because of the names are not unique in the `editapsim` function

**Comment by frank0434** [comment]
Each optimisation took about 6 days to run if using uni PC. 3GHz CPU and 16GB ram
